#!/bin/bash

echo "Running..."

set -e

    CF_ORG="INSERT-ORG-NAME"
    CF_SPACE="INSERT-SPACE-NAME"
    YYYYMM="YYYY-MM"

echo "Have you already logged into cloud.gov with a passcode? (y/n)"
read input

if [ $input == "y" ]; then
    echo "Logged in. Continuing..."
    
    cf target -o $CF_ORG -s $CF_SPACE

    echo "Targeting org and space in cloud.gov"

    echo "Running get_events.py..."
    python get_events.py $CF_ORG
    echo "Completed get_events.py..."

    echo "Running audit_events.py..."
    #Run audit_events_reporter.py
    ## input_file - file path to the .json file holding audit events created but the GitHub Action
    ## output_file - file path to where to save the MS Excel based results to
    python audit_event_reporter.py -i .\\data\\$CF_ORG\\events\\$YYYYMM.json -o AuditReport-$YYYYMM.xlsx
    
    echo "Completed audit_events reporter.py..."

    echo "Starting cleanup_report.py ..."
    python cleanup_report.py $CF_ORG $CF_SPACE $YYYYMM

    echo "Run script complete."
    exit


else if [ $input == "n" ]; then
    echo "Retrieve your passcode from cloud.gov then continue..."
    set -e

    #For sso, get temp authentication code: https://login.fr.cloud.gov/passcode
    cf login --sso -o $CF_ORG -s $CF_SPACE

    echo "Logged into cloud.gov"

    echo "Running get_events.py..."
    python get_events.py $CF_ORG
    echo "Completed get_events.py..."

    echo "Running audit_events.py..."
    #Run audit_events_reporter.py
    ## input_file - file path to the .json file holding audit events created but the GitHub Action
    ## output_file - file path to where to save the MS Excel based results to
    python audit_event_reporter.py -i .\\data\\$CF_ORG\\events\\$YYYYMM.json -o AuditReport-$YYYYMM.xlsx

    echo "Completed audit_events.py..."

    echo "Starting cleanup_report.py ..."
    python cleanup_report.py $CF_ORG $CF_SPACE $YYYYMM

    echo "Run script complete."
    exit
else if [ $input != "n" ] || [ $input != "y" ]; then
    echo "Please enter y or n. Exiting..."
    exit
fi
fi
fi