#!/bin/bash

echo "Running..."

set -e

CF_ORG="INSERT-ORG-NAME"
CF_SPACE="INSERT-SPACE-NAME"

#For sso, get temp authentication code: https://login.fr.cloud.gov/passcode
cf login --sso -o $CF_ORG -s $CF_SPACE

echo "Logged into cloud.gov"

echo "Running get_events.py..."
python get_events.py $CF_ORG
echo "Completed get_events.py..."

echo "Running audit_events.py..."
#Run audit_events_reporter.py
## input_file - file path to the .json file holding audit events created but the GitHub Action
## output_file - file path to where to save the MS Excel based results to
python audit_event_reporter.py -i .\\data\\INSERT-ORG-NAME\\events\\YYYY-MM.json -o C:\Users\username\cloudfoundry_audit_events\AuditReport-YYYY-MM.xlsx

echo "Completed audit_events.py..."

echo "Run script complete."